# Generated by Django 6.1.1 on 2026-09-29 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone_number', 'is_used', 'expires_at'], name='accounts_ph_phone_n_72bc20_idx'),
        ),
    ]
