# Generated by Django 6.1.1 on 2026-10-02 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopkeeperLegalAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_version", models.CharField(max_length=32)),
                ("privacy_policy_version", models.CharField(max_length=32)),
                ("offer_policy_version", models.CharField(max_length=32)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopkeeper_legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "terms_version",
                            "privacy_policy_version",
                            "offer_policy_version",
                        ),
                        name="unique_shopkeeper_legal_acceptance",
                    )
                ],
            },
        ),
    ]
