# Generated by Django 6.1.1 on 2026-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="INR", max_length=8),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("static", "Static price"),
                    ("dynamic", "Dynamic / custom quote"),
                ],
                default="static",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["pricing_mode", "is_active"],
                name="catalog_pro_pricing_aaf7b8_idx",
            ),
        ),
    ]
