# Generated by Django 6.1.1 on 2026-09-29 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_nearby_offer', 'New nearby offer'), ('followed_shop_offer', 'Followed shop posted'), ('saved_offer_expiring', 'Saved offer expiring'), ('price_drop', 'Price drop'), ('low_stock', 'Low stock'), ('new_message', 'New message'), ('new_review', 'New review'), ('offer_approved', 'Offer approved'), ('offer_rejected', 'Offer rejected'), ('verification_update', 'Verification update'), ('report_received', 'Report received'), ('offer_expiring', 'Offer expiring'), ('high_views', 'Offer getting many views')], max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='businesses.business')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
