# Generated by Django 6.1.1 on 2026-09-29 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('businesses', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerinteraction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='offerinteraction',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offerinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerview',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offerview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='offerinteraction',
            index=models.Index(fields=['business', 'interaction_type', 'created_at'], name='analytics_o_busines_094f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerview',
            index=models.Index(fields=['offer', 'created_at'], name='analytics_o_offer_i_c7030b_idx'),
        ),
    ]
