# Generated by Django 6.1.1 on 2026-09-29 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_price', 'Fixed Price'), ('bogo', 'Buy 1 Get 1'), ('buy_x_get_y', 'Buy X Get Y'), ('clearance', 'Clearance Sale'), ('flash_sale', 'Flash Sale'), ('limited_stock', 'Limited Stock'), ('combo', 'Combo Offer'), ('free_item', 'Free Item'), ('custom', 'Custom Offer')], default='percentage', max_length=20)),
                ('title', models.CharField(help_text="e.g. '50% OFF Men's Clothing'", max_length=200)),
                ('custom_description', models.TextField(blank=True, help_text="Used when offer_type is 'custom'")),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.PositiveIntegerField(default=0, editable=False)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_stock', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity_per_order', models.PositiveIntegerField(default=1)),
                ('max_quantity_per_order', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_deactivate_on_sold_out', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Subset of ['hot_deal', 'flash_sale', 'limited_stock', 'clearance', 'best_seller', 'new', 'popular', 'todays_deal', 'price_drop', 'last_pieces', 'exclusive', 'verified_shop']")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('sold_out', 'Sold Out')], db_index=True, default='draft', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_time', 'end_time'], name='offers_offe_status_d14b12_idx'), models.Index(fields=['business', 'status'], name='offers_offe_busines_506847_idx')],
            },
        ),
    ]
