# Generated by Django 6.1.1 on 2026-10-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Subset of ['demo', 'hot_deal', 'flash_sale', 'limited_stock', 'clearance', 'best_seller', 'new', 'popular', 'todays_deal', 'price_drop', 'last_pieces', 'exclusive', 'verified_shop']",
            ),
        ),
    ]
